name: Convert Resume to PDF

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'resume_*.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
      
      - name: Convert MD to PDF
        run: |
          # List all markdown files for debugging
          echo "Found markdown files:"
          find . -name "resume_*.md" -type f
          
          # Convert each file
          find . -name "resume_*.md" -type f | while read file; do
            echo "Converting $file to PDF"
            pdf_file="${file%.md}.pdf"
            pandoc "$file" -o "$pdf_file"
            echo "Generated $pdf_file"
          done
          
          # List generated PDFs
          echo "Generated PDF files:"
          find . -name "resume_*.pdf" -type f
      
      - name: Commit PDF
        run: |
          # Only proceed if PDFs exist
          if find . -name "resume_*.pdf" -type f | grep -q .; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            find . -name "resume_*.pdf" -type f -exec git add {} \;
            git commit -m "Auto-generate PDF from markdown" || exit 0
            git push
          else
            echo "No PDFs to commit"
            exit 0
          fi 