name: Convert Resume to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'resume_*.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
      
      - name: Convert MD to PDF
        run: |
          for file in resume_*.md; do
            if [ -f "$file" ]; then
              pdf_file="${file%.md}.pdf"
              pandoc "$file" -o "$pdf_file"
            fi
          done
      
      - name: Commit PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume_*.pdf
          git commit -m "Auto-generate PDF from markdown" || exit 0
          git push 